[pytest]

addopts = -s -vv -ra --color=yes --tb=short --maxfail=1 --durations=2 --cache-clear --disable-warnings --strict-markers --setup-show --ff

markers=
	data_cleaning: data_cleaning
	important: critical tests
	other : other

pythonpath=.

testpaths = tests

python_files = test_*.py

